#define analogPin 15

void setup() {
// put your setup code here, to run once:
Serial.begin(9600); //Set up serial connection
// Set up PWM output on pins 9,10 and 11 for different levels.
// You do it here because once it’s set up, it keeps running.
// You don’t need it in the main loop so it doesn’t interfere
// with the measurements.
// Once it’s running, attached the wire from A0 to each pin to
// see the square waveform generated by each value,

while(!Serial);
//Serial.println("Communication with Computer Established");

//
//pinMode(10, OUTPUT);
//pinMode(11, OUTPUT);
//pinMode(9, OUTPUT);
//analogWrite(9,25);
//analogWrite(10,128);
//analogWrite(11,200);
//
//// Now let’s set up a couple of basic digital pins
//pinMode(8, OUTPUT);
//digitalWrite(8, HIGH);
//pinMode(7, OUTPUT);
//digitalWrite(7, LOW);
//
//
//// Turn on Pin 13 LED so we see what’s happening there.
//
//pinMode(13, OUTPUT);
//digitalWrite(13, HIGH);


//Serial.println("Setup Complete");
}

void loop() {
  //Read analog pin
  int val = analogRead(analogPin);
  Serial.println(val, HEX);
//  Serial.println(val);
//  Serial.println();
  //Write analog value to serial port:
//  Serial.write( 0xff );                                                         
//  Serial.write( (val >> 8) & 0xff );                                            
//  Serial.write( val & 0xff );
}
